import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
test('B1 v2 producer is semantic and preserves v1 fallback', () => {
  const skill = read('skills/writing-plans/SKILL.md');
  const v2 = read('skills/writing-plans/references/compact-slices-v2.md');
  const consumer = read('skills/subagent-driven-development/references/model-routing-v1.md');
  const sdd = read('skills/subagent-driven-development/SKILL.md');
  const fixture = read('tests/fixtures/compact-slices-v2/reference-example.md');
  for (const profile of ['mechanical', 'integration', 'judgment']) assert.match(v2, new RegExp(`\\b${profile}\\b`));
  assert.match(skill, /never a concrete model or vendor/i);
  assert.match(skill, /author valid compact v1.*routing unavailable/i);
  assert.match(consumer, /blocked result means zero dispatch/i);
  assert.match(consumer, /applied acknowledgement/i);
  assert.match(consumer, /awm job routing-report --json/, 'consumer must invoke the public aggregate report contract');
  assert.match(consumer, /compact-slices\/v2/i, 'consumer must require explicit v2 contract support');
  assert.match(consumer, /policy.*capability.*otherwise.*zero dispatch/is, 'consumer must make routing readiness fail closed');
  assert.match(sdd, /references\/model-routing-v1\.md/, 'loaded SDD consumer must name sole routing reference');
  assert.match(sdd, /compact-slices\/v1` or `compact-slices\/v2/, 'loaded SDD consumer must support both schemas');
  assert.doesNotMatch(sdd, /Do not add semantic profiles/i, 'loaded SDD must not retain the obsolete v2 prohibition');
  assert.throws(() => assert.match(sdd.replace('references/model-routing-v1.md', ''), /references\/model-routing-v1\.md/), 'removing the loaded reference must fail');
  assert.throws(() => assert.match(consumer.replace(/policy.*capability.*otherwise.*zero dispatch/is, ''), /policy.*capability.*otherwise.*zero dispatch/is), 'removing the readiness consequence must fail');
  for (const profile of ['mechanical', 'integration', 'judgment']) assert.match(fixture, new RegExp(`"implementerProfile":"${profile}"`));
  assert.throws(() => assert.match(v2.replaceAll('integration', 'vendor-x'), /\bintegration\b/));
});
